# Робота з csv файлами

In [24]:
import pandas as pd
df = pd.read_csv('Bechdel_IMDB_Merge0524.csv')
df

title  year      imdbid     id  bechdelRating  \
0                          Miss Jerry  1894         9.0   9779              0   
1        Story of the Kelly Gang, The  1906       574.0   1349              1   
2                           Cleopatra  1912      2101.0   2003              2   
3               A Florida Enchantment  1914      3973.0   4457              2   
4              Birth of a Nation, The  1915      4972.0   1258              2   
...                               ...   ...         ...    ...            ...   
9713                Lisa Frankenstein  2024  21188080.0  11276              2   
9714               Love Lies Bleeding  2024  19637052.0  11294              3   
9715                       Mean Girls  2024  11762114.0  11271              3   
9716  Megamind vs. The Doom Syndicate  2024  31122323.0  11280              3   
9717                       Road House  2024   3359350.0  11303              3   

      imdbAverageRating  numVotes runtimeMinutes   genre1     genre2  \
0                   5.4     212.0             45  Romance        NaN   
1                   6.0     903.0             70   Action  Adventure   
2                   5.1     622.0            100    Drama    History   
3                   5.8     300.0             63   Comedy        NaN   
4                   6.1   26403.0            195    Drama    History   
...                 ...       ...            ...      ...        ...   
9713                6.1   16176.0            101   Comedy     Horror   
9714                6.7   23333.0            104   Action  Adventure   
9715                5.7   28257.0            112   Comedy    Musical   
9716                2.4    4076.0             83   Action  Adventure   
9717                6.2  125714.0            121   Action   Thriller   

         genre3  
0           NaN  
1     Biography  
2           NaN  
3           NaN  
4           War  
...         ...  
9713    Romance  
9714      Crime  
9715        NaN  
9716  Animation  
9717        NaN  

[9718 rows x 11 columns]

In [25]:
df[df['genre1']=='Crime']

title  year      imdbid     id  \
5                          Gretchen the Greenhorn  1916      6745.0   2008   
26    Dr. Mabuse, der Spieler - Ein Bild der Zeit  1922     13086.0   5967   
81                         Docks of New York, The  1928     18839.0   5984   
87                                    Racket, The  1928     19304.0   1972   
91                                      Blackmail  1929     19702.0   5979   
...                                           ...   ...         ...    ...   
9589                     Anatomie d&#39;une chute  2023  17009710.0  11010   
9626                                       G, The  2023  29486765.0  11154   
9639                                Infinity Pool  2023  10365998.0  10737   
9647                   Killers of the Flower Moon  2023   5537002.0  11151   
9680                                      Reptile  2023  13274016.0  11093   

      bechdelRating  imdbAverageRating  numVotes runtimeMinutes genre1  \
5                 3                6.4     537.0             58  Crime   
26                3                7.8    9199.0            242  Crime   
81                2                7.5    5049.0             76  Crime   
87                0                6.6    1592.0             84  Crime   
91                2                6.9   12035.0             85  Crime   
...             ...                ...       ...            ...    ...   
9589              3                7.7  129284.0            151  Crime   
9626              1                7.6      31.0            106  Crime   
9639              2                6.0   57399.0            117  Crime   
9647              1                7.6  244594.0            206  Crime   
9680              2                6.8   89113.0            134  Crime   

        genre2     genre3  
5        Drama    Romance  
26     Mystery   Thriller  
81       Drama  Film-Noir  
87       Drama  Film-Noir  
91       Drama   Thriller  
...        ...        ...  
9589     Drama   Thriller  
9626  Thriller        NaN  
9639    Horror    Mystery  
9647     Drama    History  
9680     Drama    Mystery  

[622 rows x 11 columns]

In [26]:
df[df['genre1']!='Drama']

title  year      imdbid     id  bechdelRating  \
0                          Miss Jerry  1894         9.0   9779              0   
1        Story of the Kelly Gang, The  1906       574.0   1349              1   
3               A Florida Enchantment  1914      3973.0   4457              2   
5              Gretchen the Greenhorn  1916      6745.0   2008              3   
7           Lady Windermere&#39;s Fan  1916    279914.0   2014              3   
...                               ...   ...         ...    ...            ...   
9713                Lisa Frankenstein  2024  21188080.0  11276              2   
9714               Love Lies Bleeding  2024  19637052.0  11294              3   
9715                       Mean Girls  2024  11762114.0  11271              3   
9716  Megamind vs. The Doom Syndicate  2024  31122323.0  11280              3   
9717                       Road House  2024   3359350.0  11303              3   

      imdbAverageRating  numVotes runtimeMinutes   genre1     genre2  \
0                   5.4     212.0             45  Romance        NaN   
1                   6.0     903.0             70   Action  Adventure   
3                   5.8     300.0             63   Comedy        NaN   
5                   6.4     537.0             58    Crime      Drama   
7                   5.3      66.0             66   Comedy      Drama   
...                 ...       ...            ...      ...        ...   
9713                6.1   16176.0            101   Comedy     Horror   
9714                6.7   23333.0            104   Action  Adventure   
9715                5.7   28257.0            112   Comedy    Musical   
9716                2.4    4076.0             83   Action  Adventure   
9717                6.2  125714.0            121   Action   Thriller   

         genre3  
0           NaN  
1     Biography  
3           NaN  
5       Romance  
7           NaN  
...         ...  
9713    Romance  
9714      Crime  
9715        NaN  
9716  Animation  
9717        NaN  

[7404 rows x 11 columns]

In [27]:
df[df['genre1'].isin(['Fantasy', 'Horror'])]

title  year      imdbid     id  \
8                                Snow White  1916      7361.0   7004   
19             Cabinet of Dr. Caligari, The  1920     10323.0   1306   
32    Nosferatu, eine Symphonie des Grauens  1922     13442.0   1307   
55                Phantom of the Opera, The  1925     16220.0   1305   
158                                  Vampyr  1932     23649.0   5910   
...                                     ...   ...         ...    ...   
9674             Priest&#39;s Exorcist, The  2023  13375076.0  10987   
9683                              SCREAM VI  2023  17663992.0  10809   
9685                                  Saw X  2023  21807222.0  11049   
9699       Winnie-the-Pooh: Blood and Honey  2023  19623240.0  10995   
9711                              Imaginary  2024  26658104.0  11322   

      bechdelRating  imdbAverageRating  numVotes runtimeMinutes   genre1  \
8                 3                6.3     444.0             63  Fantasy   
19                0                8.0   70264.0             67   Horror   
32                2                7.9  105747.0             94  Fantasy   
55                2                7.5   20156.0             93   Horror   
158               3                7.4   20587.0             75  Fantasy   
...             ...                ...       ...            ...      ...   
9674              3                6.1   84227.0            103   Horror   
9683              3                6.5  120491.0            122   Horror   
9685              3                6.6   76035.0            118   Horror   
9699              3                2.9   28826.0             84   Horror   
9711              1                4.7   10469.0            104   Horror   

        genre2    genre3  
8      Romance       NaN  
19     Mystery  Thriller  
32      Horror       NaN  
55         NaN       NaN  
158     Horror       NaN  
...        ...       ...  
9674  Thriller       NaN  
9683   Mystery  Thriller  
9685   Mystery  Thriller  
9699       NaN       NaN  
9711   Mystery  Thriller  

[549 rows x 11 columns]

In [28]:
df[df['imdbAverageRating'] >= 8.5]

title  year      imdbid     id  \
115                             City Lights  1931     21749.0   2705   
221                            Modern Times  1936     27977.0   1323   
365                              Casablanca  1942     34583.0   1076   
467               It&#39;s a Wonderful Life  1946     38650.0   2235   
676                             Rear Window  1954     47396.0   2132   
...                                     ...   ...         ...    ...   
8949                      Katharine Hepburn  2019  15324860.0  10025   
9499              Legend of Maula Jatt, The  2022   4139928.0  10606   
9678  Renaissance: A Film by Beyonc&eacute;  2023  29354040.0  11178   
9688    Spider-Man: Across the Spider-Verse  2023   9362722.0  10938   
9708                         Dune: Part Two  2024  15239678.0  11277   

      bechdelRating  imdbAverageRating  numVotes runtimeMinutes       genre1  \
115               3                8.5  196551.0             87       Comedy   
221               0                8.5  260193.0             87       Comedy   
365               1                8.5  607539.0            102        Drama   
467               3                8.6  500398.0            130        Drama   
676               3                8.5  523691.0            112      Mystery   
...             ...                ...       ...            ...          ...   
8949              3                8.7     538.0             94    Biography   
9499              3                8.7   10595.0            153       Action   
9678              3                8.6    3389.0            169  Documentary   
9688              3                8.6  374935.0            140       Action   
9708              3                8.6  420061.0            166       Action   

           genre2     genre3  
115         Drama    Romance  
221         Drama    Romance  
365       Romance        War  
467        Family    Fantasy  
676      Thriller        NaN  
...           ...        ...  
8949  Documentary        NaN  
9499        Drama    Fantasy  
9678        Music        NaN  
9688    Adventure  Animation  
9708    Adventure      Drama  

[70 rows x 11 columns]

In [29]:
df[(df['year'] >= 2000) & (df['imdbAverageRating'] > 7.4)]

title  year      imdbid     id  \
3617                          Almost Famous  2000    181875.0    877   
3618                        American Psycho  2000    144084.0     64   
3619                          Amores Perros  2000    245712.0   5792   
3623                          Battle Royale  2000    266308.0   1277   
3627                           Best in Show  2000    218839.0    928   
...                                     ...   ...         ...    ...   
9677                                Reflect  2023  14966324.0  10751   
9678  Renaissance: A Film by Beyonc&eacute;  2023  29354040.0  11178   
9688    Spider-Man: Across the Spider-Verse  2023   9362722.0  10938   
9705                                Cabrini  2024  14351082.0  11289   
9708                         Dune: Part Two  2024  15239678.0  11277   

      bechdelRating  imdbAverageRating  numVotes runtimeMinutes       genre1  \
3617              3                7.9  294255.0            122    Adventure   
3618              3                7.6  719264.0            102        Crime   
3619              1                8.1  253406.0            154        Drama   
3623              3                7.5  194894.0            114       Action   
3627              3                7.5   67117.0             90       Comedy   
...             ...                ...       ...            ...          ...   
9677              3                7.5      40.0             \N       Comedy   
9678              3                8.6    3389.0            169  Documentary   
9688              3                8.6  374935.0            140       Action   
9705              1                7.5    4825.0            142    Biography   
9708              3                8.6  420061.0            166       Action   

         genre2     genre3  
3617     Comedy      Drama  
3618      Drama     Horror  
3619   Thriller        NaN  
3623  Adventure      Drama  
3627        NaN        NaN  
...         ...        ...  
9677     Sci-Fi   Thriller  
9678      Music        NaN  
9688  Adventure  Animation  
9705      Drama        NaN  
9708  Adventure      Drama  

[769 rows x 11 columns]

In [30]:
df = pd.DataFrame({'title': df['title']})
df.to_csv('out.csv', index=False)

In [31]:
import numpy as np
age_male = np.random.uniform (low=20, high=30, size=(1,50)).flatten()
age_female = np.random. uniform (low=20, high=30, size=(1,50)). flatten()
df = pd.DataFrame({"age_female": age_female, "age_male": age_male})
df.to_csv('out.csv', index=False)

# Графіки

In [36]:
import plotly.express as px
df = pd.read_csv('Bechdel_IMDB_Merge0524.csv')
fig = px.line(df, x="year", y="imdbAverageRating", color='genre1')
fig.show()

In [37]:
partial = df [df['genre1'].isin(['Action', 'Comedy'])]
fig = px. line (partial, x="year", y="imdbAverageRating", color='genre1')
fig.show()

In [39]:
partial = df [df['year']>=1990]
fig = px. line (partial, x="year", y="imdbAverageRating", color='genre1')
fig.show()

In [42]:
partial = df [(df['imdbAverageRating'] >7) & (df['year'] >= 2000 )]
fig = px. line (partial, x="year", y="imdbAverageRating", color='genre1')
fig.show()

In [43]:

import plotly.express as px
df = pd.read_csv('iris.csv')
df
fig = px.scatter_3d(df, x='Sepal Length (cm)', y='Sepal Width (cm)', z='Petal Width (cm)', color='Species')
fig.show()


# Реалізація простих нейтронних мереж

In [46]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import layers, models
# Step 1: Read the CSV file
df = pd.read_csv('alarms.csv')
fig = px.scatter_3d (df, x='sound', y='visibility', z='alarm')
fig.show()
# Step 2: Prepare the data
X = df [['sound', 'distance', 'visibility']].values
y = df ['alarm'].values
# Step 3: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
# Step 4: Define and compile the neural network model
model = models.Sequential([
])
# layers. Dense (64, activation='relu', input_shape=(X_train.shape[1],)), # layers. Dense (32, activation=' relu'),
layers. Dense (1,input_shape=(X_train.shape[1],), activation='sigmoid')
model.compile(optimizer='adam',
loss='mean_squared_error',
metrics=['mse'])
# Step 5: Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data= (X_test, y_test))
# Step 6: Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

Epoch 1/50
25/25 [==============================] - 1s 12ms/step - loss: 0.1065 - mse: 0.1065 - val_loss: 0.1046 - val_mse: 0.1046
Epoch 2/50
25/25 [==============================] - 0s 4ms/step - loss: 0.1065 - mse: 0.1065 - val_loss: 0.1046 - val_mse: 0.1046
Epoch 3/50
25/25 [==============================] - 0s 4ms/step - loss: 0.1065 - mse: 0.1065 - val_loss: 0.1046 - val_mse: 0.1046
Epoch 4/50
25/25 [==============================] - 0s 4ms/step - loss: 0.1065 - mse: 0.1065 - val_loss: 0.1046 - val_mse: 0.1046
Epoch 5/50
25/25 [==============================] - 0s 6ms/step - loss: 0.1065 - mse: 0.1065 - val_loss: 0.1046 - val_mse: 0.1046
Epoch 6/50
25/25 [==============================] - 0s 7ms/step - loss: 0.1065 - mse: 0.1065 - val_loss: 0.1046 - val_mse: 0.1046
Epoch 7/50
25/25 [==============================] - 0s 9ms/step - loss: 0.1065 - mse: 0.1065 - val_loss: 0.1046 - val_mse: 0.1046
Epoch 8/50
25/25 [==============================] - 0s 7ms/step - loss: 0.1065 - mse: 0.1

In [47]:

# Step 7: Use the trained model to make predictions
# Example of making predictions on new data
# ['sound', 'distance', 'visibility']
new_data = np.array([
                      [0.7, 0.1, 0.7],
                      [0.3, 0.7, 0.3],
                      [0.4, 0.5, 0.3],
                      [0.6, 0.5, 0.7],
                      [0.9, 0.1, 0.9],
                      ]) # Replace with your new data
predictions = model.predict(new_data)
print("Predictions:")
print(predictions)

1/1 [==============================] - 0s 81ms/step
Predictions:
[[0.7 0.1 0.7]
 [0.3 0.7 0.3]
 [0.4 0.5 0.3]
 [0.6 0.5 0.7]
 [0.9 0.1 0.9]]
